// <auto-generated />
using System;
using EFsecond.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFsecond.Migrations
{
    [DbContext(typeof(Bank_Of_Baroda))]
    [Migration("20230515122129_StoreDB")]
    partial class StoreDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFsecond.Models.Store1", b =>
                {
                    b.Property<int>("Store1tId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Store1tId"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dateopening")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Store1tId");

                    b.HasIndex("StoreId");

                    b.ToTable("Store1");
                });

            modelBuilder.Entity("EFsecond.Models.Store2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Store2");
                });

            modelBuilder.Entity("EFsecond.Models.Store1", b =>
                {
                    b.HasOne("EFsecond.Models.Store2", "Store2")
                        .WithMany("Store1")
                        .HasForeignKey("StoreId");

                    b.Navigation("Store2");
                });

            modelBuilder.Entity("EFsecond.Models.Store2", b =>
                {
                    b.Navigation("Store1");
                });
#pragma warning restore 612, 618
        }
    }
}
